@startuml
skinparam monochrome true
left to right direction

title Graph U\nmin. cost = 49

(S1)    #Grey
(S1) --> (S2) : 10

(S2)    #Grey
(S2) --> (S3) : 8
(S2) --> (S4) : 13
(S2) --> (S5) : 24
(S2) --> (S6) : 51

(S3) --> (S4) : 14

(S4)    #Grey
(S4) --> (S5) : 9

(S5)    #Grey
(S5) --> (S6) : 17

(S6)    #Grey
@enduml
